POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "user2",
    "email": "user@gmail.com",
    "password": "1234",
    "confPassword": "1234",
    "role": "user"
}

###
//get all users
GET http://localhost:5000/users

###
//get user byId
GET http://localhost:5000/users/9083f03c-8558-44f0-89b8-b84c2badf542


###
//Update user
PATCH http://localhost:5000/users/9083f03c-8558-44f0-89b8-b84c2badf542
Content-Type: application/json

{
    "name": "admin1",
    "email": "admin@gmail.com",
    "password": "",
    "confPassword": "",
    "role": "admin"
}

###
// Delete user byID
DELETE  http://localhost:5000/users/4dba80f1-b682-4f1d-8dda-640319bc2739

###
// Login user 
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password":"admin123"
}

###
// Login admin
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password":"admin123"
}

###
// me User
GET http://localhost:5000/me

###
// Logout User
DELETE http://localhost:5000/logout

###
// Get products
GET http://localhost:5000/product

###
// Get single products
GET http://localhost:5000/product/af0e6ede-3b8c-43ee-ac85-5599076d167f



###
// POst data prodct
POST http://localhost:5000/product
Content-Type: application/json

{
    "name" : "Pangsit balado",
    "price" : 25000
}

###
//Updated product
PATCH  http://localhost:5000/product/af0e6ede-3b8c-43ee-ac85-5599076d167f
Content-Type: application/json

{
    "name" : "kulkas updated",
    "price" : 33000
}

###
//Delete product
DELETE  http://localhost:5000/product/e1cf1e3c-37a7-4def-8be5-0d79a6daa838

